# Generated by Django 4.1 on 2022-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('detalle', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
