# Generated by Django 4.1 on 2022-11-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('detalle', models.CharField(max_length=30)),
                ('tipo_producto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('detalle', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='correo',
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
