# Generated by Django 4.1 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_apellido_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
