# Generated by Django 4.1 on 2022-11-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
    ]
