# Generated by Django 4.1 on 2022-11-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_correo_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='stock',
            new_name='codigo',
        ),
    ]
