# Generated by Django 4.1 on 2022-11-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_stock_productos_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electronica',
        ),
        migrations.DeleteModel(
            name='Ropa',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='codigo',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='detalle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
