# Generated by Django 4.1 on 2022-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_electronica_delete_ropa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagenes',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
