# Generated by Django 3.1 on 2022-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221129_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.CharField(choices=[('n', 'nada'), ('ropa', 'ropa'), ('electronica', 'electro'), ('jugueteria', 'juguete')], default='n', max_length=11),
        ),
        migrations.AlterField(
            model_name='productos',
            name='detalle',
            field=models.CharField(max_length=600),
        ),
    ]
