# Generated by Django 3.1 on 2022-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221129_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('n', 'Seleccionar'), ('Prenda', 'Prendas'), ('Electronica', 'Electronica'), ('Jugueteria', 'Jugueteria')], default='nada', max_length=11),
        ),
    ]
