# Generated by Django 3.1 on 2022-11-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20221129_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
            preserve_default=False,
        ),
    ]
