# Generated by Django 3.1 on 2022-11-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221130_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.URLField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('categorias', models.CharField(choices=[('n', 'Seleccionar'), ('Prenda', 'Prendas'), ('Electronica', 'Electronica'), ('Jugueteria', 'Jugueteria')], default='n', max_length=11)),
                ('detalle', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Jugueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.URLField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('categorias', models.CharField(choices=[('n', 'Seleccionar'), ('Prenda', 'Prendas'), ('Electronica', 'Electronica'), ('Jugueteria', 'Jugueteria')], default='n', max_length=11)),
                ('detalle', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.CharField(choices=[('n', 'Seleccionar'), ('Prenda', 'Prendas'), ('Electronica', 'Electronica'), ('Jugueteria', 'Jugueteria')], default='n', max_length=11),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
