# Generated by Django 3.1 on 2022-11-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20221130_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Electronica',
        ),
        migrations.DeleteModel(
            name='Jugueteria',
        ),
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorias'),
        ),
    ]
