# Generated by Django 3.1 on 2022-11-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221130_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='talla',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Jugueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.URLField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('detalle', models.CharField(max_length=600)),
                ('categorias', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Electronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.URLField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('detalle', models.CharField(max_length=600)),
                ('categorias', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categorias')),
            ],
        ),
    ]
